# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupbox.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_box(object):
    def setupUi(self, custom_box):
        custom_box.setObjectName("custom_box")
        custom_box.resize(310, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(custom_box.sizePolicy().hasHeightForWidth())
        custom_box.setSizePolicy(sizePolicy)
        custom_box.setMaximumSize(QtCore.QSize(310, 300))
        custom_box.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(custom_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_orden_filtro = QtWidgets.QLabel(custom_box)
        self.label_orden_filtro.setObjectName("label_orden_filtro")
        self.gridLayout.addWidget(self.label_orden_filtro, 8, 0, 1, 1)
        self.checkbox_orden = QtWidgets.QCheckBox(custom_box)
        self.checkbox_orden.setObjectName("checkbox_orden")
        self.gridLayout.addWidget(self.checkbox_orden, 8, 2, 1, 1)
        self.label_ganancia = QtWidgets.QLabel(custom_box)
        self.label_ganancia.setObjectName("label_ganancia")
        self.gridLayout.addWidget(self.label_ganancia, 0, 0, 1, 1)
        self.label_Q_maximo = QtWidgets.QLabel(custom_box)
        self.label_Q_maximo.setObjectName("label_Q_maximo")
        self.gridLayout.addWidget(self.label_Q_maximo, 9, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(custom_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 2, 1, 1)
        self.label_Hz_br_mas = QtWidgets.QLabel(custom_box)
        self.label_Hz_br_mas.setObjectName("label_Hz_br_mas")
        self.gridLayout.addWidget(self.label_Hz_br_mas, 3, 2, 1, 1)
        self.checkbox_Q = QtWidgets.QCheckBox(custom_box)
        self.checkbox_Q.setObjectName("checkbox_Q")
        self.gridLayout.addWidget(self.checkbox_Q, 9, 2, 1, 1)
        self.label_desnormalizacion = QtWidgets.QLabel(custom_box)
        self.label_desnormalizacion.setObjectName("label_desnormalizacion")
        self.gridLayout.addWidget(self.label_desnormalizacion, 7, 0, 1, 1)
        self.label_dB_atenuacion_bp = QtWidgets.QLabel(custom_box)
        self.label_dB_atenuacion_bp.setObjectName("label_dB_atenuacion_bp")
        self.gridLayout.addWidget(self.label_dB_atenuacion_bp, 5, 2, 1, 1)
        self.label_dB_atenuacion_br = QtWidgets.QLabel(custom_box)
        self.label_dB_atenuacion_br.setObjectName("label_dB_atenuacion_br")
        self.gridLayout.addWidget(self.label_dB_atenuacion_br, 6, 2, 1, 1)
        self.label_atenuacion_br = QtWidgets.QLabel(custom_box)
        self.label_atenuacion_br.setObjectName("label_atenuacion_br")
        self.gridLayout.addWidget(self.label_atenuacion_br, 6, 0, 1, 1)
        self.input_atenuacion_br = QtWidgets.QLineEdit(custom_box)
        self.input_atenuacion_br.setObjectName("input_atenuacion_br")
        self.gridLayout.addWidget(self.input_atenuacion_br, 6, 1, 1, 1)
        self.label_frecuencia_fpmenos = QtWidgets.QLabel(custom_box)
        self.label_frecuencia_fpmenos.setObjectName("label_frecuencia_fpmenos")
        self.gridLayout.addWidget(self.label_frecuencia_fpmenos, 1, 0, 1, 1)
        self.label_atenuacion_bp = QtWidgets.QLabel(custom_box)
        self.label_atenuacion_bp.setObjectName("label_atenuacion_bp")
        self.gridLayout.addWidget(self.label_atenuacion_bp, 5, 0, 1, 1)
        self.input_atenuacion_bp = QtWidgets.QLineEdit(custom_box)
        self.input_atenuacion_bp.setObjectName("input_atenuacion_bp")
        self.gridLayout.addWidget(self.input_atenuacion_bp, 5, 1, 1, 1)
        self.input_ganancia = QtWidgets.QLineEdit(custom_box)
        self.input_ganancia.setObjectName("input_ganancia")
        self.gridLayout.addWidget(self.input_ganancia, 0, 1, 1, 1)
        self.input_frecuencia_bp_menos = QtWidgets.QLineEdit(custom_box)
        self.input_frecuencia_bp_menos.setObjectName("input_frecuencia_bp_menos")
        self.gridLayout.addWidget(self.input_frecuencia_bp_menos, 2, 1, 1, 1)
        self.input_frecuencia_br_mas = QtWidgets.QLineEdit(custom_box)
        self.input_frecuencia_br_mas.setObjectName("input_frecuencia_br_mas")
        self.gridLayout.addWidget(self.input_frecuencia_br_mas, 3, 1, 1, 1)
        self.input_orden_filtro = QtWidgets.QLineEdit(custom_box)
        self.input_orden_filtro.setObjectName("input_orden_filtro")
        self.gridLayout.addWidget(self.input_orden_filtro, 8, 1, 1, 1)
        self.label_frecuencia_fpmas = QtWidgets.QLabel(custom_box)
        self.label_frecuencia_fpmas.setObjectName("label_frecuencia_fpmas")
        self.gridLayout.addWidget(self.label_frecuencia_fpmas, 2, 0, 1, 1)
        self.label_Hz_bpmas = QtWidgets.QLabel(custom_box)
        self.label_Hz_bpmas.setObjectName("label_Hz_bpmas")
        self.gridLayout.addWidget(self.label_Hz_bpmas, 1, 2, 1, 1)
        self.label_dB_ganancia = QtWidgets.QLabel(custom_box)
        self.label_dB_ganancia.setObjectName("label_dB_ganancia")
        self.gridLayout.addWidget(self.label_dB_ganancia, 0, 2, 1, 1)
        self.input_frecuencia_bp_mas = QtWidgets.QLineEdit(custom_box)
        self.input_frecuencia_bp_mas.setObjectName("input_frecuencia_bp_mas")
        self.gridLayout.addWidget(self.input_frecuencia_bp_mas, 1, 1, 1, 1)
        self.label_frecuencia_famas = QtWidgets.QLabel(custom_box)
        self.label_frecuencia_famas.setObjectName("label_frecuencia_famas")
        self.gridLayout.addWidget(self.label_frecuencia_famas, 3, 0, 1, 1)
        self.input_maximo_Q = QtWidgets.QLineEdit(custom_box)
        self.input_maximo_Q.setObjectName("input_maximo_Q")
        self.gridLayout.addWidget(self.input_maximo_Q, 9, 1, 1, 1)
        self.input_desnormalizacion = QtWidgets.QLineEdit(custom_box)
        self.input_desnormalizacion.setObjectName("input_desnormalizacion")
        self.gridLayout.addWidget(self.input_desnormalizacion, 7, 1, 1, 1)
        self.label_frecuencia_famenos = QtWidgets.QLabel(custom_box)
        self.label_frecuencia_famenos.setObjectName("label_frecuencia_famenos")
        self.gridLayout.addWidget(self.label_frecuencia_famenos, 4, 0, 1, 1)
        self.input_frecuencia_br_menos = QtWidgets.QLineEdit(custom_box)
        self.input_frecuencia_br_menos.setObjectName("input_frecuencia_br_menos")
        self.gridLayout.addWidget(self.input_frecuencia_br_menos, 4, 1, 1, 1)
        self.label_Hz_bpmenos = QtWidgets.QLabel(custom_box)
        self.label_Hz_bpmenos.setObjectName("label_Hz_bpmenos")
        self.gridLayout.addWidget(self.label_Hz_bpmenos, 2, 2, 1, 1)
        self.label_Hz_br_menos = QtWidgets.QLabel(custom_box)
        self.label_Hz_br_menos.setObjectName("label_Hz_br_menos")
        self.gridLayout.addWidget(self.label_Hz_br_menos, 4, 2, 1, 1)

        self.retranslateUi(custom_box)
        QtCore.QMetaObject.connectSlotsByName(custom_box)

    def retranslateUi(self, custom_box):
        _translate = QtCore.QCoreApplication.translate
        custom_box.setWindowTitle(_translate("custom_box", "GroupBox"))
        custom_box.setTitle(_translate("custom_box", "Filter Configuration"))
        self.label_orden_filtro.setText(_translate("custom_box", "Filter Order:"))
        self.checkbox_orden.setText(_translate("custom_box", "Fixed"))
        self.label_ganancia.setText(_translate("custom_box", "Gain:"))
        self.label_Q_maximo.setText(_translate("custom_box", "Maximun Q:"))
        self.label_2.setText(_translate("custom_box", "%"))
        self.label_Hz_br_mas.setText(_translate("custom_box", "Hz"))
        self.checkbox_Q.setText(_translate("custom_box", "Fixed"))
        self.label_desnormalizacion.setText(_translate("custom_box", "Denormalization"))
        self.label_dB_atenuacion_bp.setText(_translate("custom_box", "dB"))
        self.label_dB_atenuacion_br.setText(_translate("custom_box", "dB"))
        self.label_atenuacion_br.setText(_translate("custom_box", "Stopband Attenuation(Aa):"))
        self.label_frecuencia_fpmenos.setText(_translate("custom_box", "Passband Freq-  (Fp-):"))
        self.label_atenuacion_bp.setText(_translate("custom_box", "Passband Attenuation(Ap):"))
        self.label_frecuencia_fpmas.setText(_translate("custom_box", "Passband Freq+ (Fp+)"))
        self.label_Hz_bpmas.setText(_translate("custom_box", "Hz"))
        self.label_dB_ganancia.setText(_translate("custom_box", "dB"))
        self.label_frecuencia_famas.setText(_translate("custom_box", "Stopband Freq (Fa+):"))
        self.label_frecuencia_famenos.setText(_translate("custom_box", "Stopband Freq- (Fa-)"))
        self.label_Hz_bpmenos.setText(_translate("custom_box", "Hz"))
        self.label_Hz_br_menos.setText(_translate("custom_box", "Hz"))
